# Generated by Django 5.0.4 on 2024-04-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
