# Generated by Django 5.0.4 on 2024-05-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0003_experiment_result_outimage_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
