# Generated by Django 5.0.4 on 2024-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0008_explanationmethod_alter_experiment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationmethod',
            name='name',
            field=models.CharField(choices=[('shap', 'shap'), ('lime', 'lime'), ('gcam', 'gradcam'), ('igrad', 'integratedGradient')], max_length=30),
        ),
    ]
