# Generated by Django 5.0.4 on 2024-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0009_alter_explanationmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationmethod',
            name='name',
            field=models.CharField(choices=[('1', 'lime'), ('2', 'gradcam'), ('3', 'integrated'), ('4', 'shap')], max_length=30),
        ),
    ]
