# Generated by Django 5.0.4 on 2024-05-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0012_alter_explanationmethod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocoCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='outimage',
            name='input_image',
        ),
        migrations.RemoveField(
            model_name='result',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='result',
            name='status',
        ),
        migrations.AddField(
            model_name='config',
            name='use_coco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outimage',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xaiapp.explanationmethod'),
        ),
        migrations.AddField(
            model_name='outimage',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xaiapp.result'),
        ),
        migrations.AddField(
            model_name='result',
            name='elapsed_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='explanation_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xaiapp.explanationmethod'),
        ),
        migrations.AddField(
            model_name='result',
            name='pred_top1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='result_intersect',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='second_pass_pred',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='use_coco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='coco_categories',
            field=models.ManyToManyField(to='xaiapp.cococategories'),
        ),
        migrations.AddField(
            model_name='result',
            name='coco_categories',
            field=models.ManyToManyField(to='xaiapp.cococategories'),
        ),
        migrations.CreateModel(
            name='ExplanationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neural_network', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('methods', models.ManyToManyField(to='xaiapp.explanationmethod')),
            ],
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
