# Generated by Django 5.0.4 on 2024-06-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0016_alter_experiment_status_and_more'),
        ('xaiapp', '0016_result_coco_masks_result_filtered_result_final_and_more'),
    ]

    operations = [
    ]
