# Generated by Django 5.0.6 on 2024-06-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0017_merge_20240603_2025'),
        ('xaiapp', '0018_remove_result_pred_top1_explanationresult_pred_top1'),
    ]

    operations = [
    ]
