# Generated by Django 5.0.4 on 2024-06-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0019_merge_20240603_2038'),
        ('xaiapp', '0019_merge_20240603_2045'),
    ]

    operations = [
    ]
