# Generated by Django 5.0.6 on 2024-06-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xaiapp', '0020_merge_20240603_2052'),
        ('xaiapp', '0020_merge_20240603_2121'),
    ]

    operations = [
    ]
